### ISSUE TITLE
Repository 리드미에 관하여..

### ISSUE THREAD

**Issue by Jinwon-Dev** [JUNOSHON/react-seminar-review#1]
react-tech, react-seminar과는 다른 Repository인가요?
간단하게라도 리드미를 작성해주면 좋을 것 같아요.

**Comment by JUNOSHON** [comment]
react-tech 와 react-seminar, react-seminar-review 의 각 레포지터리에 대한 README.md 를 수정했습니다.
코멘트 감사합니다!
